### ISSUE TITLE
The schema example might be misleading, missing a gym

### ISSUE THREAD

**Issue by AliSoftware** [fastlane/fastlane.tools#32]
It seems odd to me on that schema to have a lane which only calls `scan` (which will build and run the tests but not create and archive) and then call `pilot` (which would need an archive/ipa to upload), so I find that 2nd lane in the example schema misleading 😉 

![Schema](https://fastlane.tools/assets/img/intro-fastlane-tree.png)

**Comment by Richard-510** [comment]
Thanks for the solution,its really helpful [nox](https://www.nox.plus/).

**Comment by joshdholtz** [comment]
Closing this since a little out of date 😉
